name: panel_kit
description: "Dashboard builw with Flutter"
version: 0.0.12
homepage: "https://github.com/maciejdudek92/panel-kit/tree/main/"

platforms:
  web:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  toastification: ^2.3.0
  get_it: ^8.0.1
  flutter_breadcrumb: ^1.0.1
  uuid: ^4.5.1
  collection: ^1.18.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - google_fonts/
